/**
 * API do Futebolcard
 * Futebolcard manipulation API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDoFutebolcard);
  }
}(this, function(expect, ApiDoFutebolcard) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDoFutebolcard.EventsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EventsApi', function() {
    describe('eventsEventIdGet', function() {
      it('should call eventsEventIdGet successfully', function(done) {
        //uncomment below and update the code to test eventsEventIdGet
        //instance.eventsEventIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('eventsEventIdSectorsGet', function() {
      it('should call eventsEventIdSectorsGet successfully', function(done) {
        //uncomment below and update the code to test eventsEventIdSectorsGet
        //instance.eventsEventIdSectorsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('eventsEventIdSectorsSectorIdGet', function() {
      it('should call eventsEventIdSectorsSectorIdGet successfully', function(done) {
        //uncomment below and update the code to test eventsEventIdSectorsSectorIdGet
        //instance.eventsEventIdSectorsSectorIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('eventsEventIdSectorsSectorIdSubsectorsGet', function() {
      it('should call eventsEventIdSectorsSectorIdSubsectorsGet successfully', function(done) {
        //uncomment below and update the code to test eventsEventIdSectorsSectorIdSubsectorsGet
        //instance.eventsEventIdSectorsSectorIdSubsectorsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('eventsEventIdSectorsSectorIdSubsectorsSubsectorIdGet', function() {
      it('should call eventsEventIdSectorsSectorIdSubsectorsSubsectorIdGet successfully', function(done) {
        //uncomment below and update the code to test eventsEventIdSectorsSectorIdSubsectorsSubsectorIdGet
        //instance.eventsEventIdSectorsSectorIdSubsectorsSubsectorIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('eventsGet', function() {
      it('should call eventsGet successfully', function(done) {
        //uncomment below and update the code to test eventsGet
        //instance.eventsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
