/**
 * API do Futebolcard
 * Futebolcard manipulation API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDoFutebolcard);
  }
}(this, function(expect, ApiDoFutebolcard) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDoFutebolcard.Events();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Events', function() {
    it('should create an instance of Events', function() {
      // uncomment below and update the code to test Events
      //var instane = new ApiDoFutebolcard.Events();
      //expect(instance).to.be.a(ApiDoFutebolcard.Events);
    });

    it('should have the property eventId (base name: "eventId")', function() {
      // uncomment below and update the code to test the property eventId
      //var instane = new ApiDoFutebolcard.Events();
      //expect(instance).to.be();
    });

    it('should have the property categorieName (base name: "categorieName")', function() {
      // uncomment below and update the code to test the property categorieName
      //var instane = new ApiDoFutebolcard.Events();
      //expect(instance).to.be();
    });

    it('should have the property internetSaleStartDate (base name: "internetSaleStartDate")', function() {
      // uncomment below and update the code to test the property internetSaleStartDate
      //var instane = new ApiDoFutebolcard.Events();
      //expect(instance).to.be();
    });

    it('should have the property internetSaleEndDate (base name: "internetSaleEndDate")', function() {
      // uncomment below and update the code to test the property internetSaleEndDate
      //var instane = new ApiDoFutebolcard.Events();
      //expect(instance).to.be();
    });

    it('should have the property saleStartDate (base name: "saleStartDate")', function() {
      // uncomment below and update the code to test the property saleStartDate
      //var instane = new ApiDoFutebolcard.Events();
      //expect(instance).to.be();
    });

    it('should have the property saleEndDate (base name: "saleEndDate")', function() {
      // uncomment below and update the code to test the property saleEndDate
      //var instane = new ApiDoFutebolcard.Events();
      //expect(instance).to.be();
    });

    it('should have the property memberSaleStartDate (base name: "memberSaleStartDate")', function() {
      // uncomment below and update the code to test the property memberSaleStartDate
      //var instane = new ApiDoFutebolcard.Events();
      //expect(instance).to.be();
    });

    it('should have the property memberSaleEndDate (base name: "memberSaleEndDate")', function() {
      // uncomment below and update the code to test the property memberSaleEndDate
      //var instane = new ApiDoFutebolcard.Events();
      //expect(instance).to.be();
    });

    it('should have the property eventDate (base name: "eventDate")', function() {
      // uncomment below and update the code to test the property eventDate
      //var instane = new ApiDoFutebolcard.Events();
      //expect(instance).to.be();
    });

    it('should have the property eventTime (base name: "eventTime")', function() {
      // uncomment below and update the code to test the property eventTime
      //var instane = new ApiDoFutebolcard.Events();
      //expect(instance).to.be();
    });

    it('should have the property stadiumName (base name: "stadiumName")', function() {
      // uncomment below and update the code to test the property stadiumName
      //var instane = new ApiDoFutebolcard.Events();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "city")', function() {
      // uncomment below and update the code to test the property city
      //var instane = new ApiDoFutebolcard.Events();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instane = new ApiDoFutebolcard.Events();
      //expect(instance).to.be();
    });

    it('should have the property principalClub (base name: "principalClub")', function() {
      // uncomment below and update the code to test the property principalClub
      //var instane = new ApiDoFutebolcard.Events();
      //expect(instance).to.be();
    });

    it('should have the property opponentClub (base name: "opponentClub")', function() {
      // uncomment below and update the code to test the property opponentClub
      //var instane = new ApiDoFutebolcard.Events();
      //expect(instance).to.be();
    });

    it('should have the property principalClubImage (base name: "principalClubImage")', function() {
      // uncomment below and update the code to test the property principalClubImage
      //var instane = new ApiDoFutebolcard.Events();
      //expect(instance).to.be();
    });

    it('should have the property opponentClubImage (base name: "opponentClubImage")', function() {
      // uncomment below and update the code to test the property opponentClubImage
      //var instane = new ApiDoFutebolcard.Events();
      //expect(instance).to.be();
    });

    it('should have the property expressSale (base name: "expressSale")', function() {
      // uncomment below and update the code to test the property expressSale
      //var instane = new ApiDoFutebolcard.Events();
      //expect(instance).to.be();
    });

  });

}));
