/**
 * API Agillitas Cartões Pré-pagos
 * API para manipular recursos relacionadas aos  cartões pré-pagos Agillitas.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/NovoCartaoPortador'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./NovoCartaoPortador'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiAgillitasCartesPrPagos) {
      root.ApiAgillitasCartesPrPagos = {};
    }
    root.ApiAgillitasCartesPrPagos.NovoCartao = factory(root.ApiAgillitasCartesPrPagos.ApiClient, root.ApiAgillitasCartesPrPagos.NovoCartaoPortador);
  }
}(this, function(ApiClient, NovoCartaoPortador) {
  'use strict';




  /**
   * The NovoCartao model module.
   * @module model/NovoCartao
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>NovoCartao</code>.
   * @alias module:model/NovoCartao
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>NovoCartao</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NovoCartao} obj Optional instance to populate.
   * @return {module:model/NovoCartao} The populated <code>NovoCartao</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('idCartao')) {
        obj['idCartao'] = ApiClient.convertToType(data['idCartao'], 'String');
      }
      if (data.hasOwnProperty('valor')) {
        obj['valor'] = ApiClient.convertToType(data['valor'], 'Number');
      }
      if (data.hasOwnProperty('contrasenha')) {
        obj['contrasenha'] = ApiClient.convertToType(data['contrasenha'], 'String');
      }
      if (data.hasOwnProperty('portador')) {
        obj['portador'] = NovoCartaoPortador.constructFromObject(data['portador']);
      }
    }
    return obj;
  }

  /**
   * Número identificador referente ao proxy do cartão.
   * @member {String} idCartao
   */
  exports.prototype['idCartao'] = undefined;
  /**
   * Valor monetário  a ser creditado na conta do cartão.
   * @member {Number} valor
   */
  exports.prototype['valor'] = undefined;
  /**
   * Contrassenha do cartão
   * @member {String} contrasenha
   */
  exports.prototype['contrasenha'] = undefined;
  /**
   * @member {module:model/NovoCartaoPortador} portador
   */
  exports.prototype['portador'] = undefined;



  return exports;
}));


