/**
 * API Agillitas Cartões Pré-pagos
 * API para manipular recursos relacionadas aos  cartões pré-pagos Agillitas.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiAgillitasCartesPrPagos) {
      root.ApiAgillitasCartesPrPagos = {};
    }
    root.ApiAgillitasCartesPrPagos.SetTransferencia = factory(root.ApiAgillitasCartesPrPagos.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SetTransferencia model module.
   * @module model/SetTransferencia
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SetTransferencia</code>.
   * @alias module:model/SetTransferencia
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>SetTransferencia</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SetTransferencia} obj Optional instance to populate.
   * @return {module:model/SetTransferencia} The populated <code>SetTransferencia</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('idCartao')) {
        obj['idCartao'] = ApiClient.convertToType(data['idCartao'], 'String');
      }
      if (data.hasOwnProperty('idCartaoDestino')) {
        obj['idCartaoDestino'] = ApiClient.convertToType(data['idCartaoDestino'], 'String');
      }
      if (data.hasOwnProperty('valor')) {
        obj['valor'] = ApiClient.convertToType(data['valor'], 'Number');
      }
      if (data.hasOwnProperty('senha')) {
        obj['senha'] = ApiClient.convertToType(data['senha'], 'String');
      }
    }
    return obj;
  }

  /**
   * número identificador referente ao proxy do cartão origem de transferência.
   * @member {String} idCartao
   */
  exports.prototype['idCartao'] = undefined;
  /**
   * número identificador referente ao proxy do cartão destino de transferência.
   * @member {String} idCartaoDestino
   */
  exports.prototype['idCartaoDestino'] = undefined;
  /**
   * Valor monetário  a ser transferido.
   * @member {Number} valor
   */
  exports.prototype['valor'] = undefined;
  /**
   * Senha do cartão.
   * @member {String} senha
   */
  exports.prototype['senha'] = undefined;



  return exports;
}));


