/**
 * API Agillitas Cartões Pré-pagos
 * API para manipular recursos relacionadas aos  cartões pré-pagos Agillitas.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiAgillitasCartesPrPagos);
  }
}(this, function(expect, ApiAgillitasCartesPrPagos) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiAgillitasCartesPrPagos.NovoCartaoPortadorEndereco();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NovoCartaoPortadorEndereco', function() {
    it('should create an instance of NovoCartaoPortadorEndereco', function() {
      // uncomment below and update the code to test NovoCartaoPortadorEndereco
      //var instane = new ApiAgillitasCartesPrPagos.NovoCartaoPortadorEndereco();
      //expect(instance).to.be.a(ApiAgillitasCartesPrPagos.NovoCartaoPortadorEndereco);
    });

    it('should have the property logradouro (base name: "logradouro")', function() {
      // uncomment below and update the code to test the property logradouro
      //var instane = new ApiAgillitasCartesPrPagos.NovoCartaoPortadorEndereco();
      //expect(instance).to.be();
    });

    it('should have the property complemento (base name: "complemento")', function() {
      // uncomment below and update the code to test the property complemento
      //var instane = new ApiAgillitasCartesPrPagos.NovoCartaoPortadorEndereco();
      //expect(instance).to.be();
    });

    it('should have the property cidade (base name: "cidade")', function() {
      // uncomment below and update the code to test the property cidade
      //var instane = new ApiAgillitasCartesPrPagos.NovoCartaoPortadorEndereco();
      //expect(instance).to.be();
    });

    it('should have the property estado (base name: "estado")', function() {
      // uncomment below and update the code to test the property estado
      //var instane = new ApiAgillitasCartesPrPagos.NovoCartaoPortadorEndereco();
      //expect(instance).to.be();
    });

    it('should have the property pais (base name: "pais")', function() {
      // uncomment below and update the code to test the property pais
      //var instane = new ApiAgillitasCartesPrPagos.NovoCartaoPortadorEndereco();
      //expect(instance).to.be();
    });

    it('should have the property codigoPostal (base name: "codigoPostal")', function() {
      // uncomment below and update the code to test the property codigoPostal
      //var instane = new ApiAgillitasCartesPrPagos.NovoCartaoPortadorEndereco();
      //expect(instance).to.be();
    });

  });

}));
