/**
 * API dos Correios
 * API de rastreios de Objetos Postais
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiDosCorreios) {
      root.ApiDosCorreios = {};
    }
    root.ApiDosCorreios.Endereco = factory(root.ApiDosCorreios.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Endereco model module.
   * @module model/Endereco
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Endereco</code>.
   * Customer Model
   * @alias module:model/Endereco
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>Endereco</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Endereco} obj Optional instance to populate.
   * @return {module:model/Endereco} The populated <code>Endereco</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('logradouro')) {
        obj['logradouro'] = ApiClient.convertToType(data['logradouro'], 'String');
      }
      if (data.hasOwnProperty('bairro')) {
        obj['bairro'] = ApiClient.convertToType(data['bairro'], 'String');
      }
      if (data.hasOwnProperty('municipio')) {
        obj['municipio'] = ApiClient.convertToType(data['municipio'], 'String');
      }
      if (data.hasOwnProperty('uf')) {
        obj['uf'] = ApiClient.convertToType(data['uf'], 'String');
      }
    }
    return obj;
  }

  /**
   * Nome do logradouro
   * @member {String} logradouro
   */
  exports.prototype['logradouro'] = undefined;
  /**
   * Nome do Bairro
   * @member {String} bairro
   */
  exports.prototype['bairro'] = undefined;
  /**
   * Nome do municipio
   * @member {String} municipio
   */
  exports.prototype['municipio'] = undefined;
  /**
   * Estado
   * @member {String} uf
   */
  exports.prototype['uf'] = undefined;



  return exports;
}));


