/**
 * API dos Correios
 * API de rastreios de Objetos Postais
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiDosCorreios) {
      root.ApiDosCorreios = {};
    }
    root.ApiDosCorreios.Eventos = factory(root.ApiDosCorreios.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Eventos model module.
   * @module model/Eventos
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Eventos</code>.
   * Customer Model
   * @alias module:model/Eventos
   * @class
   */
  var exports = function() {
    var _this = this;



















  };

  /**
   * Constructs a <code>Eventos</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Eventos} obj Optional instance to populate.
   * @return {module:model/Eventos} The populated <code>Eventos</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('codigoObjeto')) {
        obj['codigoObjeto'] = ApiClient.convertToType(data['codigoObjeto'], 'String');
      }
      if (data.hasOwnProperty('tipoEvento')) {
        obj['tipoEvento'] = ApiClient.convertToType(data['tipoEvento'], 'String');
      }
      if (data.hasOwnProperty('statusEvento')) {
        obj['statusEvento'] = ApiClient.convertToType(data['statusEvento'], 'Number');
      }
      if (data.hasOwnProperty('descricaoEvento')) {
        obj['descricaoEvento'] = ApiClient.convertToType(data['descricaoEvento'], 'String');
      }
      if (data.hasOwnProperty('nomeUnidade')) {
        obj['nomeUnidade'] = ApiClient.convertToType(data['nomeUnidade'], 'String');
      }
      if (data.hasOwnProperty('codigoSRO')) {
        obj['codigoSRO'] = ApiClient.convertToType(data['codigoSRO'], 'String');
      }
      if (data.hasOwnProperty('municipio')) {
        obj['municipio'] = ApiClient.convertToType(data['municipio'], 'String');
      }
      if (data.hasOwnProperty('uf')) {
        obj['uf'] = ApiClient.convertToType(data['uf'], 'String');
      }
      if (data.hasOwnProperty('codigoMCU')) {
        obj['codigoMCU'] = ApiClient.convertToType(data['codigoMCU'], 'String');
      }
      if (data.hasOwnProperty('codigoDR')) {
        obj['codigoDR'] = ApiClient.convertToType(data['codigoDR'], 'String');
      }
      if (data.hasOwnProperty('siglaDR')) {
        obj['siglaDR'] = ApiClient.convertToType(data['siglaDR'], 'String');
      }
      if (data.hasOwnProperty('numeroLista')) {
        obj['numeroLista'] = ApiClient.convertToType(data['numeroLista'], 'String');
      }
      if (data.hasOwnProperty('estacao')) {
        obj['estacao'] = ApiClient.convertToType(data['estacao'], 'Number');
      }
      if (data.hasOwnProperty('usuario')) {
        obj['usuario'] = ApiClient.convertToType(data['usuario'], 'String');
      }
      if (data.hasOwnProperty('dataGravacao')) {
        obj['dataGravacao'] = ApiClient.convertToType(data['dataGravacao'], 'String');
      }
      if (data.hasOwnProperty('entregador')) {
        obj['entregador'] = ApiClient.convertToType(data['entregador'], 'String');
      }
      if (data.hasOwnProperty('dataCriacao')) {
        obj['dataCriacao'] = ApiClient.convertToType(data['dataCriacao'], 'String');
      }
      if (data.hasOwnProperty('acaoBloqueio')) {
        obj['acaoBloqueio'] = ApiClient.convertToType(data['acaoBloqueio'], 'Number');
      }
    }
    return obj;
  }

  /**
   * Código do Objeto
   * @member {String} codigoObjeto
   */
  exports.prototype['codigoObjeto'] = undefined;
  /**
   * Tipo do Evento
   * @member {String} tipoEvento
   */
  exports.prototype['tipoEvento'] = undefined;
  /**
   * Status do Evento
   * @member {Number} statusEvento
   */
  exports.prototype['statusEvento'] = undefined;
  /**
   * Descrição do Evento
   * @member {String} descricaoEvento
   */
  exports.prototype['descricaoEvento'] = undefined;
  /**
   * Nome da Unidade
   * @member {String} nomeUnidade
   */
  exports.prototype['nomeUnidade'] = undefined;
  /**
   * Código do SRO
   * @member {String} codigoSRO
   */
  exports.prototype['codigoSRO'] = undefined;
  /**
   * Nome do Municipio
   * @member {String} municipio
   */
  exports.prototype['municipio'] = undefined;
  /**
   * Sigla do Estado
   * @member {String} uf
   */
  exports.prototype['uf'] = undefined;
  /**
   * Código do MCU
   * @member {String} codigoMCU
   */
  exports.prototype['codigoMCU'] = undefined;
  /**
   * Código DR
   * @member {String} codigoDR
   */
  exports.prototype['codigoDR'] = undefined;
  /**
   * Sigla do DR
   * @member {String} siglaDR
   */
  exports.prototype['siglaDR'] = undefined;
  /**
   * Número na Lista
   * @member {String} numeroLista
   */
  exports.prototype['numeroLista'] = undefined;
  /**
   * Estação
   * @member {Number} estacao
   */
  exports.prototype['estacao'] = undefined;
  /**
   * Nome do Usuário
   * @member {String} usuario
   */
  exports.prototype['usuario'] = undefined;
  /**
   * Data da Gravação
   * @member {String} dataGravacao
   */
  exports.prototype['dataGravacao'] = undefined;
  /**
   * Entregador
   * @member {String} entregador
   */
  exports.prototype['entregador'] = undefined;
  /**
   * Data de Criação
   * @member {String} dataCriacao
   */
  exports.prototype['dataCriacao'] = undefined;
  /**
   * Ação de Bloqueio
   * @member {Number} acaoBloqueio
   */
  exports.prototype['acaoBloqueio'] = undefined;



  return exports;
}));


