/**
 * API dos Correios
 * API de rastreios de Objetos Postais
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiDosCorreios) {
      root.ApiDosCorreios = {};
    }
    root.ApiDosCorreios.FaixaCEP = factory(root.ApiDosCorreios.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The FaixaCEP model module.
   * @module model/FaixaCEP
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>FaixaCEP</code>.
   * Customer Model
   * @alias module:model/FaixaCEP
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>FaixaCEP</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FaixaCEP} obj Optional instance to populate.
   * @return {module:model/FaixaCEP} The populated <code>FaixaCEP</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('nome')) {
        obj['nome'] = ApiClient.convertToType(data['nome'], 'String');
      }
      if (data.hasOwnProperty('inicio')) {
        obj['inicio'] = ApiClient.convertToType(data['inicio'], 'String');
      }
      if (data.hasOwnProperty('fim')) {
        obj['fim'] = ApiClient.convertToType(data['fim'], 'String');
      }
    }
    return obj;
  }

  /**
   * Nome do municipio
   * @member {String} nome
   */
  exports.prototype['nome'] = undefined;
  /**
   * inicio da faixa de CEP
   * @member {String} inicio
   */
  exports.prototype['inicio'] = undefined;
  /**
   * Fim da faixa de CEP
   * @member {String} fim
   */
  exports.prototype['fim'] = undefined;



  return exports;
}));


