/**
 * API dos Correios
 * API de rastreios de Objetos Postais
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Eventos'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Eventos'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiDosCorreios) {
      root.ApiDosCorreios = {};
    }
    root.ApiDosCorreios.ObjetoPostal = factory(root.ApiDosCorreios.ApiClient, root.ApiDosCorreios.Eventos);
  }
}(this, function(ApiClient, Eventos) {
  'use strict';




  /**
   * The ObjetoPostal model module.
   * @module model/ObjetoPostal
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ObjetoPostal</code>.
   * Postal Object model
   * @alias module:model/ObjetoPostal
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ObjetoPostal</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ObjetoPostal} obj Optional instance to populate.
   * @return {module:model/ObjetoPostal} The populated <code>ObjetoPostal</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('numero')) {
        obj['numero'] = ApiClient.convertToType(data['numero'], 'String');
      }
      if (data.hasOwnProperty('eventos')) {
        obj['eventos'] = ApiClient.convertToType(data['eventos'], [Eventos]);
      }
    }
    return obj;
  }

  /**
   * Número do Objeto Postal
   * @member {String} numero
   */
  exports.prototype['numero'] = undefined;
  /**
   * @member {Array.<module:model/Eventos>} eventos
   */
  exports.prototype['eventos'] = undefined;



  return exports;
}));


