/*
 * API dos Correios
 * API de rastreios de Objetos Postais
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.InlineResponse2002;
import io.swagger.client.model.InlineResponse400;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EndereosApi
 */
@Ignore
public class EndereosApiTest {

    private final EndereosApi api = new EndereosApi();

    
    /**
     * 
     *
     * Pesquisa pelo endereço de um dado CEP.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void enderecosCepGetTest() throws ApiException {
        String clientId = null;
        String accessToken = null;
        String cep = null;
        List<InlineResponse2002> response = api.enderecosCepGet(clientId, accessToken, cep);

        // TODO: test validations
    }
    
}
