/*
 * API dos Correios
 * API de rastreios de Objetos Postais
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Customer Model
 */
@ApiModel(description = "Customer Model")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-23T11:14:49.586Z")
public class InlineResponse2004 {
  @SerializedName("tipoEvento")
  private String tipoEvento = null;

  @SerializedName("statusEvento")
  private Integer statusEvento = null;

  @SerializedName("descricaoEvento")
  private String descricaoEvento = null;

  public InlineResponse2004 tipoEvento(String tipoEvento) {
    this.tipoEvento = tipoEvento;
    return this;
  }

   /**
   * TIpo do Evento
   * @return tipoEvento
  **/
  @ApiModelProperty(example = "BDE", value = "TIpo do Evento")
  public String getTipoEvento() {
    return tipoEvento;
  }

  public void setTipoEvento(String tipoEvento) {
    this.tipoEvento = tipoEvento;
  }

  public InlineResponse2004 statusEvento(Integer statusEvento) {
    this.statusEvento = statusEvento;
    return this;
  }

   /**
   * Status do Evento
   * @return statusEvento
  **/
  @ApiModelProperty(example = "1", value = "Status do Evento")
  public Integer getStatusEvento() {
    return statusEvento;
  }

  public void setStatusEvento(Integer statusEvento) {
    this.statusEvento = statusEvento;
  }

  public InlineResponse2004 descricaoEvento(String descricaoEvento) {
    this.descricaoEvento = descricaoEvento;
    return this;
  }

   /**
   * Descrição do Evento
   * @return descricaoEvento
  **/
  @ApiModelProperty(example = "Entregue", value = "Descrição do Evento")
  public String getDescricaoEvento() {
    return descricaoEvento;
  }

  public void setDescricaoEvento(String descricaoEvento) {
    this.descricaoEvento = descricaoEvento;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2004 inlineResponse2004 = (InlineResponse2004) o;
    return Objects.equals(this.tipoEvento, inlineResponse2004.tipoEvento) &&
        Objects.equals(this.statusEvento, inlineResponse2004.statusEvento) &&
        Objects.equals(this.descricaoEvento, inlineResponse2004.descricaoEvento);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tipoEvento, statusEvento, descricaoEvento);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2004 {\n");
    
    sb.append("    tipoEvento: ").append(toIndentedString(tipoEvento)).append("\n");
    sb.append("    statusEvento: ").append(toIndentedString(statusEvento)).append("\n");
    sb.append("    descricaoEvento: ").append(toIndentedString(descricaoEvento)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

