/*
 * API do Futebolcard
 * Futebolcard manipulation API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SectorDetail
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-23T10:50:44.652Z")
public class SectorDetail {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("selectSeats")
  private String selectSeats = null;

  @SerializedName("available")
  private Integer available = null;

  @SerializedName("hasTickets")
  private Integer hasTickets = null;

  public SectorDetail id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "831313", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public SectorDetail name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "Setor C", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SectorDetail selectSeats(String selectSeats) {
    this.selectSeats = selectSeats;
    return this;
  }

   /**
   * Get selectSeats
   * @return selectSeats
  **/
  @ApiModelProperty(example = "1", value = "")
  public String getSelectSeats() {
    return selectSeats;
  }

  public void setSelectSeats(String selectSeats) {
    this.selectSeats = selectSeats;
  }

  public SectorDetail available(Integer available) {
    this.available = available;
    return this;
  }

   /**
   * Get available
   * @return available
  **/
  @ApiModelProperty(example = "0", value = "")
  public Integer getAvailable() {
    return available;
  }

  public void setAvailable(Integer available) {
    this.available = available;
  }

  public SectorDetail hasTickets(Integer hasTickets) {
    this.hasTickets = hasTickets;
    return this;
  }

   /**
   * Get hasTickets
   * @return hasTickets
  **/
  @ApiModelProperty(example = "1", value = "")
  public Integer getHasTickets() {
    return hasTickets;
  }

  public void setHasTickets(Integer hasTickets) {
    this.hasTickets = hasTickets;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SectorDetail sectorDetail = (SectorDetail) o;
    return Objects.equals(this.id, sectorDetail.id) &&
        Objects.equals(this.name, sectorDetail.name) &&
        Objects.equals(this.selectSeats, sectorDetail.selectSeats) &&
        Objects.equals(this.available, sectorDetail.available) &&
        Objects.equals(this.hasTickets, sectorDetail.hasTickets);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, selectSeats, available, hasTickets);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SectorDetail {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    selectSeats: ").append(toIndentedString(selectSeats)).append("\n");
    sb.append("    available: ").append(toIndentedString(available)).append("\n");
    sb.append("    hasTickets: ").append(toIndentedString(hasTickets)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

