/*
 * API do Futebolcard
 * Futebolcard manipulation API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.InlineResponse2002Subsectors;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * SubSectors
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-23T10:50:44.652Z")
public class SubSectors {
  @SerializedName("subsectors")
  private List<InlineResponse2002Subsectors> subsectors = null;

  public SubSectors subsectors(List<InlineResponse2002Subsectors> subsectors) {
    this.subsectors = subsectors;
    return this;
  }

  public SubSectors addSubsectorsItem(InlineResponse2002Subsectors subsectorsItem) {
    if (this.subsectors == null) {
      this.subsectors = new ArrayList<InlineResponse2002Subsectors>();
    }
    this.subsectors.add(subsectorsItem);
    return this;
  }

   /**
   * Get subsectors
   * @return subsectors
  **/
  @ApiModelProperty(value = "")
  public List<InlineResponse2002Subsectors> getSubsectors() {
    return subsectors;
  }

  public void setSubsectors(List<InlineResponse2002Subsectors> subsectors) {
    this.subsectors = subsectors;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubSectors subSectors = (SubSectors) o;
    return Objects.equals(this.subsectors, subSectors.subsectors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subsectors);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubSectors {\n");
    
    sb.append("    subsectors: ").append(toIndentedString(subsectors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

