/**
 * API Agillitas Cartões Pré-pagos
 * API para manipular recursos relacionadas aos  cartões pré-pagos Agillitas.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sensedia.agillitas.api.v1.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class NovoCartaoPortadorEndereco {
  
  @SerializedName("logradouro")
  private String logradouro = null;
  @SerializedName("complemento")
  private String complemento = null;
  @SerializedName("cidade")
  private String cidade = null;
  @SerializedName("estado")
  private String estado = null;
  @SerializedName("pais")
  private String pais = null;
  @SerializedName("codigoPostal")
  private String codigoPostal = null;

  /**
   * Nome Endereço  do portador do cartão.
   **/
  @ApiModelProperty(value = "Nome Endereço  do portador do cartão.")
  public String getLogradouro() {
    return logradouro;
  }
  public void setLogradouro(String logradouro) {
    this.logradouro = logradouro;
  }

  /**
   * Complemento do logradouro do portador do cartão.
   **/
  @ApiModelProperty(value = "Complemento do logradouro do portador do cartão.")
  public String getComplemento() {
    return complemento;
  }
  public void setComplemento(String complemento) {
    this.complemento = complemento;
  }

  /**
   * Nome cidade do portador do cartão.
   **/
  @ApiModelProperty(value = "Nome cidade do portador do cartão.")
  public String getCidade() {
    return cidade;
  }
  public void setCidade(String cidade) {
    this.cidade = cidade;
  }

  /**
   * Sigla do estado do portador do cartão.
   **/
  @ApiModelProperty(value = "Sigla do estado do portador do cartão.")
  public String getEstado() {
    return estado;
  }
  public void setEstado(String estado) {
    this.estado = estado;
  }

  /**
   * País do portador = \"Brasil\"
   **/
  @ApiModelProperty(value = "País do portador = \"Brasil\"")
  public String getPais() {
    return pais;
  }
  public void setPais(String pais) {
    this.pais = pais;
  }

  /**
   * Código de endereçamento postal do portador do cartão (CEP). Não deve conter pontos ou hífen.
   **/
  @ApiModelProperty(value = "Código de endereçamento postal do portador do cartão (CEP). Não deve conter pontos ou hífen.")
  public String getCodigoPostal() {
    return codigoPostal;
  }
  public void setCodigoPostal(String codigoPostal) {
    this.codigoPostal = codigoPostal;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NovoCartaoPortadorEndereco novoCartaoPortadorEndereco = (NovoCartaoPortadorEndereco) o;
    return (this.logradouro == null ? novoCartaoPortadorEndereco.logradouro == null : this.logradouro.equals(novoCartaoPortadorEndereco.logradouro)) &&
        (this.complemento == null ? novoCartaoPortadorEndereco.complemento == null : this.complemento.equals(novoCartaoPortadorEndereco.complemento)) &&
        (this.cidade == null ? novoCartaoPortadorEndereco.cidade == null : this.cidade.equals(novoCartaoPortadorEndereco.cidade)) &&
        (this.estado == null ? novoCartaoPortadorEndereco.estado == null : this.estado.equals(novoCartaoPortadorEndereco.estado)) &&
        (this.pais == null ? novoCartaoPortadorEndereco.pais == null : this.pais.equals(novoCartaoPortadorEndereco.pais)) &&
        (this.codigoPostal == null ? novoCartaoPortadorEndereco.codigoPostal == null : this.codigoPostal.equals(novoCartaoPortadorEndereco.codigoPostal));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.logradouro == null ? 0: this.logradouro.hashCode());
    result = 31 * result + (this.complemento == null ? 0: this.complemento.hashCode());
    result = 31 * result + (this.cidade == null ? 0: this.cidade.hashCode());
    result = 31 * result + (this.estado == null ? 0: this.estado.hashCode());
    result = 31 * result + (this.pais == null ? 0: this.pais.hashCode());
    result = 31 * result + (this.codigoPostal == null ? 0: this.codigoPostal.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class NovoCartaoPortadorEndereco {\n");
    
    sb.append("  logradouro: ").append(logradouro).append("\n");
    sb.append("  complemento: ").append(complemento).append("\n");
    sb.append("  cidade: ").append(cidade).append("\n");
    sb.append("  estado: ").append(estado).append("\n");
    sb.append("  pais: ").append(pais).append("\n");
    sb.append("  codigoPostal: ").append(codigoPostal).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
