/**
 * API Agillitas Cartões Pré-pagos
 * API para manipular recursos relacionadas aos  cartões pré-pagos Agillitas.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sensedia.agillitas.api.v1.model;

import com.sensedia.agillitas.api.v1.model.EnderecoPortador;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Portador {
  
  @SerializedName("nome")
  private String nome = null;
  @SerializedName("email")
  private String email = null;
  @SerializedName("celular")
  private String celular = null;
  @SerializedName("endereco")
  private EnderecoPortador endereco = null;

  /**
   * Nome do portador do cartão.
   **/
  @ApiModelProperty(value = "Nome do portador do cartão.")
  public String getNome() {
    return nome;
  }
  public void setNome(String nome) {
    this.nome = nome;
  }

  /**
   * Endereço  de e-mail do portador do cartão.
   **/
  @ApiModelProperty(value = "Endereço  de e-mail do portador do cartão.")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   * Numero do telefone celular do portador do cartão.
   **/
  @ApiModelProperty(value = "Numero do telefone celular do portador do cartão.")
  public String getCelular() {
    return celular;
  }
  public void setCelular(String celular) {
    this.celular = celular;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public EnderecoPortador getEndereco() {
    return endereco;
  }
  public void setEndereco(EnderecoPortador endereco) {
    this.endereco = endereco;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Portador portador = (Portador) o;
    return (this.nome == null ? portador.nome == null : this.nome.equals(portador.nome)) &&
        (this.email == null ? portador.email == null : this.email.equals(portador.email)) &&
        (this.celular == null ? portador.celular == null : this.celular.equals(portador.celular)) &&
        (this.endereco == null ? portador.endereco == null : this.endereco.equals(portador.endereco));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.nome == null ? 0: this.nome.hashCode());
    result = 31 * result + (this.email == null ? 0: this.email.hashCode());
    result = 31 * result + (this.celular == null ? 0: this.celular.hashCode());
    result = 31 * result + (this.endereco == null ? 0: this.endereco.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Portador {\n");
    
    sb.append("  nome: ").append(nome).append("\n");
    sb.append("  email: ").append(email).append("\n");
    sb.append("  celular: ").append(celular).append("\n");
    sb.append("  endereco: ").append(endereco).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
