/**
 * API Agillitas Cartões Pré-pagos
 * API para manipular recursos relacionadas aos  cartões pré-pagos Agillitas.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sensedia.agillitas.api.v1.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SetPagamento {
  
  @SerializedName("idCartao")
  private String idCartao = null;
  @SerializedName("senha")
  private String senha = null;
  @SerializedName("codigoBarras")
  private String codigoBarras = null;

  /**
   * número identificador referente ao proxy do cartão.
   **/
  @ApiModelProperty(value = "número identificador referente ao proxy do cartão.")
  public String getIdCartao() {
    return idCartao;
  }
  public void setIdCartao(String idCartao) {
    this.idCartao = idCartao;
  }

  /**
   * Senha do cartão.
   **/
  @ApiModelProperty(value = "Senha do cartão.")
  public String getSenha() {
    return senha;
  }
  public void setSenha(String senha) {
    this.senha = senha;
  }

  /**
   * Código de pagamento identificado no documento (boleto).
   **/
  @ApiModelProperty(value = "Código de pagamento identificado no documento (boleto).")
  public String getCodigoBarras() {
    return codigoBarras;
  }
  public void setCodigoBarras(String codigoBarras) {
    this.codigoBarras = codigoBarras;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SetPagamento setPagamento = (SetPagamento) o;
    return (this.idCartao == null ? setPagamento.idCartao == null : this.idCartao.equals(setPagamento.idCartao)) &&
        (this.senha == null ? setPagamento.senha == null : this.senha.equals(setPagamento.senha)) &&
        (this.codigoBarras == null ? setPagamento.codigoBarras == null : this.codigoBarras.equals(setPagamento.codigoBarras));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.idCartao == null ? 0: this.idCartao.hashCode());
    result = 31 * result + (this.senha == null ? 0: this.senha.hashCode());
    result = 31 * result + (this.codigoBarras == null ? 0: this.codigoBarras.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SetPagamento {\n");
    
    sb.append("  idCartao: ").append(idCartao).append("\n");
    sb.append("  senha: ").append(senha).append("\n");
    sb.append("  codigoBarras: ").append(codigoBarras).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
