/**
 * API Agillitas Cartões Pré-pagos
 * API para manipular recursos relacionadas aos  cartões pré-pagos Agillitas.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sensedia.agillitas.api.v1.model;

import com.sensedia.agillitas.api.v1.model.CadastroBenificiario;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class TransferenciaCadastroBenificiario {
  
  @SerializedName("beneficiario")
  private CadastroBenificiario beneficiario = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public CadastroBenificiario getBeneficiario() {
    return beneficiario;
  }
  public void setBeneficiario(CadastroBenificiario beneficiario) {
    this.beneficiario = beneficiario;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransferenciaCadastroBenificiario transferenciaCadastroBenificiario = (TransferenciaCadastroBenificiario) o;
    return (this.beneficiario == null ? transferenciaCadastroBenificiario.beneficiario == null : this.beneficiario.equals(transferenciaCadastroBenificiario.beneficiario));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.beneficiario == null ? 0: this.beneficiario.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransferenciaCadastroBenificiario {\n");
    
    sb.append("  beneficiario: ").append(beneficiario).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
