/**
 * API Agillitas Cartões Pré-pagos
 * API para manipular recursos relacionadas aos  cartões pré-pagos Agillitas.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sensedia.agillitas.api.v1.model;

import com.sensedia.agillitas.api.v1.model.SetTransferencia;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Transferencia {
  
  @SerializedName("transferencia")
  private SetTransferencia transferencia = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public SetTransferencia getTransferencia() {
    return transferencia;
  }
  public void setTransferencia(SetTransferencia transferencia) {
    this.transferencia = transferencia;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Transferencia transferencia = (Transferencia) o;
    return (this.transferencia == null ? transferencia.transferencia == null : this.transferencia.equals(transferencia.transferencia));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.transferencia == null ? 0: this.transferencia.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Transferencia {\n");
    
    sb.append("  transferencia: ").append(transferencia).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
