/**
 * API dos Correios
 * API de rastreios de Objetos Postais
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDosCorreios);
  }
}(this, function(expect, ApiDosCorreios) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDosCorreios.CalculoPrecoFrete();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CalculoPrecoFrete', function() {
    it('should create an instance of CalculoPrecoFrete', function() {
      // uncomment below and update the code to test CalculoPrecoFrete
      //var instane = new ApiDosCorreios.CalculoPrecoFrete();
      //expect(instance).to.be.a(ApiDosCorreios.CalculoPrecoFrete);
    });

    it('should have the property codigo (base name: "codigo")', function() {
      // uncomment below and update the code to test the property codigo
      //var instane = new ApiDosCorreios.CalculoPrecoFrete();
      //expect(instance).to.be();
    });

    it('should have the property httpStatus (base name: "httpStatus")', function() {
      // uncomment below and update the code to test the property httpStatus
      //var instane = new ApiDosCorreios.CalculoPrecoFrete();
      //expect(instance).to.be();
    });

    it('should have the property valor (base name: "valor")', function() {
      // uncomment below and update the code to test the property valor
      //var instane = new ApiDosCorreios.CalculoPrecoFrete();
      //expect(instance).to.be();
    });

    it('should have the property adicionalMaoPropria (base name: "adicionalMaoPropria")', function() {
      // uncomment below and update the code to test the property adicionalMaoPropria
      //var instane = new ApiDosCorreios.CalculoPrecoFrete();
      //expect(instance).to.be();
    });

    it('should have the property adicionalAvisoRecebimento (base name: "adicionalAvisoRecebimento")', function() {
      // uncomment below and update the code to test the property adicionalAvisoRecebimento
      //var instane = new ApiDosCorreios.CalculoPrecoFrete();
      //expect(instance).to.be();
    });

    it('should have the property adicionalValorDeclarado (base name: "adicionalValorDeclarado")', function() {
      // uncomment below and update the code to test the property adicionalValorDeclarado
      //var instane = new ApiDosCorreios.CalculoPrecoFrete();
      //expect(instance).to.be();
    });

    it('should have the property valorSemAdicionais (base name: "valorSemAdicionais")', function() {
      // uncomment below and update the code to test the property valorSemAdicionais
      //var instane = new ApiDosCorreios.CalculoPrecoFrete();
      //expect(instance).to.be();
    });

    it('should have the property resultado (base name: "resultado")', function() {
      // uncomment below and update the code to test the property resultado
      //var instane = new ApiDosCorreios.CalculoPrecoFrete();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new ApiDosCorreios.CalculoPrecoFrete();
      //expect(instance).to.be();
    });

    it('should have the property detalhes (base name: "detalhes")', function() {
      // uncomment below and update the code to test the property detalhes
      //var instane = new ApiDosCorreios.CalculoPrecoFrete();
      //expect(instance).to.be();
    });

  });

}));
