/**
 * API dos Correios
 * API de rastreios de Objetos Postais
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDosCorreios);
  }
}(this, function(expect, ApiDosCorreios) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDosCorreios.DetalhesEventos();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DetalhesEventos', function() {
    it('should create an instance of DetalhesEventos', function() {
      // uncomment below and update the code to test DetalhesEventos
      //var instane = new ApiDosCorreios.DetalhesEventos();
      //expect(instance).to.be.a(ApiDosCorreios.DetalhesEventos);
    });

    it('should have the property tipoEvento (base name: "tipoEvento")', function() {
      // uncomment below and update the code to test the property tipoEvento
      //var instane = new ApiDosCorreios.DetalhesEventos();
      //expect(instance).to.be();
    });

    it('should have the property statusEvento (base name: "statusEvento")', function() {
      // uncomment below and update the code to test the property statusEvento
      //var instane = new ApiDosCorreios.DetalhesEventos();
      //expect(instance).to.be();
    });

    it('should have the property descricaoEvento (base name: "descricaoEvento")', function() {
      // uncomment below and update the code to test the property descricaoEvento
      //var instane = new ApiDosCorreios.DetalhesEventos();
      //expect(instance).to.be();
    });

  });

}));
