/**
 * API Agillitas Cartões Pré-pagos
 * API para manipular recursos relacionadas aos  cartões pré-pagos Agillitas.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiAgillitasCartesPrPagos);
  }
}(this, function(expect, ApiAgillitasCartesPrPagos) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiAgillitasCartesPrPagos.CartoesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CartoesApi', function() {
    describe('cartoesIdCartaoExtratoGet', function() {
      it('should call cartoesIdCartaoExtratoGet successfully', function(done) {
        //uncomment below and update the code to test cartoesIdCartaoExtratoGet
        //instance.cartoesIdCartaoExtratoGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cartoesIdCartaoPortadorGet', function() {
      it('should call cartoesIdCartaoPortadorGet successfully', function(done) {
        //uncomment below and update the code to test cartoesIdCartaoPortadorGet
        //instance.cartoesIdCartaoPortadorGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cartoesIdCartaoSaldoGet', function() {
      it('should call cartoesIdCartaoSaldoGet successfully', function(done) {
        //uncomment below and update the code to test cartoesIdCartaoSaldoGet
        //instance.cartoesIdCartaoSaldoGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cartoesIdCartaoSaldoPut', function() {
      it('should call cartoesIdCartaoSaldoPut successfully', function(done) {
        //uncomment below and update the code to test cartoesIdCartaoSaldoPut
        //instance.cartoesIdCartaoSaldoPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cartoesIdCartaoStatusGet', function() {
      it('should call cartoesIdCartaoStatusGet successfully', function(done) {
        //uncomment below and update the code to test cartoesIdCartaoStatusGet
        //instance.cartoesIdCartaoStatusGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cartoesIdCartaoStatusPut', function() {
      it('should call cartoesIdCartaoStatusPut successfully', function(done) {
        //uncomment below and update the code to test cartoesIdCartaoStatusPut
        //instance.cartoesIdCartaoStatusPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cartoesPost', function() {
      it('should call cartoesPost successfully', function(done) {
        //uncomment below and update the code to test cartoesPost
        //instance.cartoesPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
