/**
 * API do Futebolcard
 * Futebolcard manipulation API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiDoFutebolcard) {
      root.ApiDoFutebolcard = {};
    }
    root.ApiDoFutebolcard.Events = factory(root.ApiDoFutebolcard.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Events model module.
   * @module model/Events
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Events</code>.
   * @alias module:model/Events
   * @class
   */
  var exports = function() {
    var _this = this;



















  };

  /**
   * Constructs a <code>Events</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Events} obj Optional instance to populate.
   * @return {module:model/Events} The populated <code>Events</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('eventId')) {
        obj['eventId'] = ApiClient.convertToType(data['eventId'], 'String');
      }
      if (data.hasOwnProperty('categorieName')) {
        obj['categorieName'] = ApiClient.convertToType(data['categorieName'], 'String');
      }
      if (data.hasOwnProperty('internetSaleStartDate')) {
        obj['internetSaleStartDate'] = ApiClient.convertToType(data['internetSaleStartDate'], 'String');
      }
      if (data.hasOwnProperty('internetSaleEndDate')) {
        obj['internetSaleEndDate'] = ApiClient.convertToType(data['internetSaleEndDate'], 'String');
      }
      if (data.hasOwnProperty('saleStartDate')) {
        obj['saleStartDate'] = ApiClient.convertToType(data['saleStartDate'], 'String');
      }
      if (data.hasOwnProperty('saleEndDate')) {
        obj['saleEndDate'] = ApiClient.convertToType(data['saleEndDate'], 'String');
      }
      if (data.hasOwnProperty('memberSaleStartDate')) {
        obj['memberSaleStartDate'] = ApiClient.convertToType(data['memberSaleStartDate'], 'String');
      }
      if (data.hasOwnProperty('memberSaleEndDate')) {
        obj['memberSaleEndDate'] = ApiClient.convertToType(data['memberSaleEndDate'], 'String');
      }
      if (data.hasOwnProperty('eventDate')) {
        obj['eventDate'] = ApiClient.convertToType(data['eventDate'], 'String');
      }
      if (data.hasOwnProperty('eventTime')) {
        obj['eventTime'] = ApiClient.convertToType(data['eventTime'], 'String');
      }
      if (data.hasOwnProperty('stadiumName')) {
        obj['stadiumName'] = ApiClient.convertToType(data['stadiumName'], 'String');
      }
      if (data.hasOwnProperty('city')) {
        obj['city'] = ApiClient.convertToType(data['city'], 'String');
      }
      if (data.hasOwnProperty('state')) {
        obj['state'] = ApiClient.convertToType(data['state'], 'String');
      }
      if (data.hasOwnProperty('principalClub')) {
        obj['principalClub'] = ApiClient.convertToType(data['principalClub'], 'String');
      }
      if (data.hasOwnProperty('opponentClub')) {
        obj['opponentClub'] = ApiClient.convertToType(data['opponentClub'], 'String');
      }
      if (data.hasOwnProperty('principalClubImage')) {
        obj['principalClubImage'] = ApiClient.convertToType(data['principalClubImage'], 'String');
      }
      if (data.hasOwnProperty('opponentClubImage')) {
        obj['opponentClubImage'] = ApiClient.convertToType(data['opponentClubImage'], 'String');
      }
      if (data.hasOwnProperty('expressSale')) {
        obj['expressSale'] = ApiClient.convertToType(data['expressSale'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} eventId
   */
  exports.prototype['eventId'] = undefined;
  /**
   * @member {String} categorieName
   */
  exports.prototype['categorieName'] = undefined;
  /**
   * @member {String} internetSaleStartDate
   */
  exports.prototype['internetSaleStartDate'] = undefined;
  /**
   * @member {String} internetSaleEndDate
   */
  exports.prototype['internetSaleEndDate'] = undefined;
  /**
   * @member {String} saleStartDate
   */
  exports.prototype['saleStartDate'] = undefined;
  /**
   * @member {String} saleEndDate
   */
  exports.prototype['saleEndDate'] = undefined;
  /**
   * @member {String} memberSaleStartDate
   */
  exports.prototype['memberSaleStartDate'] = undefined;
  /**
   * @member {String} memberSaleEndDate
   */
  exports.prototype['memberSaleEndDate'] = undefined;
  /**
   * @member {String} eventDate
   */
  exports.prototype['eventDate'] = undefined;
  /**
   * @member {String} eventTime
   */
  exports.prototype['eventTime'] = undefined;
  /**
   * @member {String} stadiumName
   */
  exports.prototype['stadiumName'] = undefined;
  /**
   * @member {String} city
   */
  exports.prototype['city'] = undefined;
  /**
   * @member {String} state
   */
  exports.prototype['state'] = undefined;
  /**
   * @member {String} principalClub
   */
  exports.prototype['principalClub'] = undefined;
  /**
   * @member {String} opponentClub
   */
  exports.prototype['opponentClub'] = undefined;
  /**
   * @member {String} principalClubImage
   */
  exports.prototype['principalClubImage'] = undefined;
  /**
   * @member {String} opponentClubImage
   */
  exports.prototype['opponentClubImage'] = undefined;
  /**
   * @member {String} expressSale
   */
  exports.prototype['expressSale'] = undefined;



  return exports;
}));


