/**
 * API do Futebolcard
 * Futebolcard manipulation API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SectorDetail'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SectorDetail'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiDoFutebolcard) {
      root.ApiDoFutebolcard = {};
    }
    root.ApiDoFutebolcard.Gates = factory(root.ApiDoFutebolcard.ApiClient, root.ApiDoFutebolcard.SectorDetail);
  }
}(this, function(ApiClient, SectorDetail) {
  'use strict';




  /**
   * The Gates model module.
   * @module model/Gates
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Gates</code>.
   * @alias module:model/Gates
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>Gates</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Gates} obj Optional instance to populate.
   * @return {module:model/Gates} The populated <code>Gates</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('gateId')) {
        obj['gateId'] = ApiClient.convertToType(data['gateId'], 'String');
      }
      if (data.hasOwnProperty('gateName')) {
        obj['gateName'] = ApiClient.convertToType(data['gateName'], 'String');
      }
      if (data.hasOwnProperty('sectors')) {
        obj['sectors'] = ApiClient.convertToType(data['sectors'], [SectorDetail]);
      }
    }
    return obj;
  }

  /**
   * @member {String} gateId
   */
  exports.prototype['gateId'] = undefined;
  /**
   * @member {String} gateName
   */
  exports.prototype['gateName'] = undefined;
  /**
   * @member {Array.<module:model/SectorDetail>} sectors
   */
  exports.prototype['sectors'] = undefined;



  return exports;
}));


