/**
 * API do Futebolcard
 * Futebolcard manipulation API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Seat'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Seat'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiDoFutebolcard) {
      root.ApiDoFutebolcard = {};
    }
    root.ApiDoFutebolcard.Row = factory(root.ApiDoFutebolcard.ApiClient, root.ApiDoFutebolcard.Seat);
  }
}(this, function(ApiClient, Seat) {
  'use strict';




  /**
   * The Row model module.
   * @module model/Row
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Row</code>.
   * @alias module:model/Row
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>Row</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Row} obj Optional instance to populate.
   * @return {module:model/Row} The populated <code>Row</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('rowId')) {
        obj['rowId'] = ApiClient.convertToType(data['rowId'], 'String');
      }
      if (data.hasOwnProperty('rowAlias')) {
        obj['rowAlias'] = ApiClient.convertToType(data['rowAlias'], 'String');
      }
      if (data.hasOwnProperty('rowName')) {
        obj['rowName'] = ApiClient.convertToType(data['rowName'], 'String');
      }
      if (data.hasOwnProperty('seats')) {
        obj['seats'] = ApiClient.convertToType(data['seats'], [Seat]);
      }
    }
    return obj;
  }

  /**
   * @member {String} rowId
   */
  exports.prototype['rowId'] = undefined;
  /**
   * @member {String} rowAlias
   */
  exports.prototype['rowAlias'] = undefined;
  /**
   * @member {String} rowName
   */
  exports.prototype['rowName'] = undefined;
  /**
   * @member {Array.<module:model/Seat>} seats
   */
  exports.prototype['seats'] = undefined;



  return exports;
}));


