/**
 * API Agillitas Cartões Pré-pagos
 * API para manipular recursos relacionadas aos  cartões pré-pagos Agillitas.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MsgErro', 'model/Pagamento'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/MsgErro'), require('../model/Pagamento'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiAgillitasCartesPrPagos) {
      root.ApiAgillitasCartesPrPagos = {};
    }
    root.ApiAgillitasCartesPrPagos.PagamentosApi = factory(root.ApiAgillitasCartesPrPagos.ApiClient, root.ApiAgillitasCartesPrPagos.MsgErro, root.ApiAgillitasCartesPrPagos.Pagamento);
  }
}(this, function(ApiClient, MsgErro, Pagamento) {
  'use strict';

  /**
   * Pagamentos service.
   * @module api/PagamentosApi
   * @version 1.0.0
   */

  /**
   * Constructs a new PagamentosApi. 
   * @alias module:api/PagamentosApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the pagamentosPost operation.
     * @callback module:api/PagamentosApi~pagamentosPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Pagamento de boletos.
     * &lt;p&gt;Permite o pagamento de boletos.&lt;/p&gt;
     * @param {String} clientId Identificador do cliente utilizado na autenticação.
     * @param {String} accessToken Token de acesso utilizado na autenticação.
     * @param {module:model/Pagamento} boleto Objeto de requisição
     * @param {module:api/PagamentosApi~pagamentosPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.pagamentosPost = function(clientId, accessToken, boleto, callback) {
      var postBody = boleto;

      // verify the required parameter 'clientId' is set
      if (clientId === undefined || clientId === null) {
        throw new Error("Missing the required parameter 'clientId' when calling pagamentosPost");
      }

      // verify the required parameter 'accessToken' is set
      if (accessToken === undefined || accessToken === null) {
        throw new Error("Missing the required parameter 'accessToken' when calling pagamentosPost");
      }

      // verify the required parameter 'boleto' is set
      if (boleto === undefined || boleto === null) {
        throw new Error("Missing the required parameter 'boleto' when calling pagamentosPost");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
        'client_id': clientId,
        'access_token': accessToken
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/pagamentos', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
