/**
 * API do Futebolcard
 * Futebolcard manipulation API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.sensedia.futcardclient.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Events {
  
  @SerializedName("eventId")
  private String eventId = null;
  @SerializedName("categorieName")
  private String categorieName = null;
  @SerializedName("internetSaleStartDate")
  private String internetSaleStartDate = null;
  @SerializedName("internetSaleEndDate")
  private String internetSaleEndDate = null;
  @SerializedName("saleStartDate")
  private String saleStartDate = null;
  @SerializedName("saleEndDate")
  private String saleEndDate = null;
  @SerializedName("memberSaleStartDate")
  private String memberSaleStartDate = null;
  @SerializedName("memberSaleEndDate")
  private String memberSaleEndDate = null;
  @SerializedName("eventDate")
  private String eventDate = null;
  @SerializedName("eventTime")
  private String eventTime = null;
  @SerializedName("stadiumName")
  private String stadiumName = null;
  @SerializedName("city")
  private String city = null;
  @SerializedName("state")
  private String state = null;
  @SerializedName("principalClub")
  private String principalClub = null;
  @SerializedName("opponentClub")
  private String opponentClub = null;
  @SerializedName("principalClubImage")
  private String principalClubImage = null;
  @SerializedName("opponentClubImage")
  private String opponentClubImage = null;
  @SerializedName("expressSale")
  private String expressSale = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEventId() {
    return eventId;
  }
  public void setEventId(String eventId) {
    this.eventId = eventId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCategorieName() {
    return categorieName;
  }
  public void setCategorieName(String categorieName) {
    this.categorieName = categorieName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getInternetSaleStartDate() {
    return internetSaleStartDate;
  }
  public void setInternetSaleStartDate(String internetSaleStartDate) {
    this.internetSaleStartDate = internetSaleStartDate;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getInternetSaleEndDate() {
    return internetSaleEndDate;
  }
  public void setInternetSaleEndDate(String internetSaleEndDate) {
    this.internetSaleEndDate = internetSaleEndDate;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSaleStartDate() {
    return saleStartDate;
  }
  public void setSaleStartDate(String saleStartDate) {
    this.saleStartDate = saleStartDate;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSaleEndDate() {
    return saleEndDate;
  }
  public void setSaleEndDate(String saleEndDate) {
    this.saleEndDate = saleEndDate;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMemberSaleStartDate() {
    return memberSaleStartDate;
  }
  public void setMemberSaleStartDate(String memberSaleStartDate) {
    this.memberSaleStartDate = memberSaleStartDate;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMemberSaleEndDate() {
    return memberSaleEndDate;
  }
  public void setMemberSaleEndDate(String memberSaleEndDate) {
    this.memberSaleEndDate = memberSaleEndDate;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEventDate() {
    return eventDate;
  }
  public void setEventDate(String eventDate) {
    this.eventDate = eventDate;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEventTime() {
    return eventTime;
  }
  public void setEventTime(String eventTime) {
    this.eventTime = eventTime;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getStadiumName() {
    return stadiumName;
  }
  public void setStadiumName(String stadiumName) {
    this.stadiumName = stadiumName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCity() {
    return city;
  }
  public void setCity(String city) {
    this.city = city;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getState() {
    return state;
  }
  public void setState(String state) {
    this.state = state;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPrincipalClub() {
    return principalClub;
  }
  public void setPrincipalClub(String principalClub) {
    this.principalClub = principalClub;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getOpponentClub() {
    return opponentClub;
  }
  public void setOpponentClub(String opponentClub) {
    this.opponentClub = opponentClub;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPrincipalClubImage() {
    return principalClubImage;
  }
  public void setPrincipalClubImage(String principalClubImage) {
    this.principalClubImage = principalClubImage;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getOpponentClubImage() {
    return opponentClubImage;
  }
  public void setOpponentClubImage(String opponentClubImage) {
    this.opponentClubImage = opponentClubImage;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getExpressSale() {
    return expressSale;
  }
  public void setExpressSale(String expressSale) {
    this.expressSale = expressSale;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Events events = (Events) o;
    return (this.eventId == null ? events.eventId == null : this.eventId.equals(events.eventId)) &&
        (this.categorieName == null ? events.categorieName == null : this.categorieName.equals(events.categorieName)) &&
        (this.internetSaleStartDate == null ? events.internetSaleStartDate == null : this.internetSaleStartDate.equals(events.internetSaleStartDate)) &&
        (this.internetSaleEndDate == null ? events.internetSaleEndDate == null : this.internetSaleEndDate.equals(events.internetSaleEndDate)) &&
        (this.saleStartDate == null ? events.saleStartDate == null : this.saleStartDate.equals(events.saleStartDate)) &&
        (this.saleEndDate == null ? events.saleEndDate == null : this.saleEndDate.equals(events.saleEndDate)) &&
        (this.memberSaleStartDate == null ? events.memberSaleStartDate == null : this.memberSaleStartDate.equals(events.memberSaleStartDate)) &&
        (this.memberSaleEndDate == null ? events.memberSaleEndDate == null : this.memberSaleEndDate.equals(events.memberSaleEndDate)) &&
        (this.eventDate == null ? events.eventDate == null : this.eventDate.equals(events.eventDate)) &&
        (this.eventTime == null ? events.eventTime == null : this.eventTime.equals(events.eventTime)) &&
        (this.stadiumName == null ? events.stadiumName == null : this.stadiumName.equals(events.stadiumName)) &&
        (this.city == null ? events.city == null : this.city.equals(events.city)) &&
        (this.state == null ? events.state == null : this.state.equals(events.state)) &&
        (this.principalClub == null ? events.principalClub == null : this.principalClub.equals(events.principalClub)) &&
        (this.opponentClub == null ? events.opponentClub == null : this.opponentClub.equals(events.opponentClub)) &&
        (this.principalClubImage == null ? events.principalClubImage == null : this.principalClubImage.equals(events.principalClubImage)) &&
        (this.opponentClubImage == null ? events.opponentClubImage == null : this.opponentClubImage.equals(events.opponentClubImage)) &&
        (this.expressSale == null ? events.expressSale == null : this.expressSale.equals(events.expressSale));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.eventId == null ? 0: this.eventId.hashCode());
    result = 31 * result + (this.categorieName == null ? 0: this.categorieName.hashCode());
    result = 31 * result + (this.internetSaleStartDate == null ? 0: this.internetSaleStartDate.hashCode());
    result = 31 * result + (this.internetSaleEndDate == null ? 0: this.internetSaleEndDate.hashCode());
    result = 31 * result + (this.saleStartDate == null ? 0: this.saleStartDate.hashCode());
    result = 31 * result + (this.saleEndDate == null ? 0: this.saleEndDate.hashCode());
    result = 31 * result + (this.memberSaleStartDate == null ? 0: this.memberSaleStartDate.hashCode());
    result = 31 * result + (this.memberSaleEndDate == null ? 0: this.memberSaleEndDate.hashCode());
    result = 31 * result + (this.eventDate == null ? 0: this.eventDate.hashCode());
    result = 31 * result + (this.eventTime == null ? 0: this.eventTime.hashCode());
    result = 31 * result + (this.stadiumName == null ? 0: this.stadiumName.hashCode());
    result = 31 * result + (this.city == null ? 0: this.city.hashCode());
    result = 31 * result + (this.state == null ? 0: this.state.hashCode());
    result = 31 * result + (this.principalClub == null ? 0: this.principalClub.hashCode());
    result = 31 * result + (this.opponentClub == null ? 0: this.opponentClub.hashCode());
    result = 31 * result + (this.principalClubImage == null ? 0: this.principalClubImage.hashCode());
    result = 31 * result + (this.opponentClubImage == null ? 0: this.opponentClubImage.hashCode());
    result = 31 * result + (this.expressSale == null ? 0: this.expressSale.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Events {\n");
    
    sb.append("  eventId: ").append(eventId).append("\n");
    sb.append("  categorieName: ").append(categorieName).append("\n");
    sb.append("  internetSaleStartDate: ").append(internetSaleStartDate).append("\n");
    sb.append("  internetSaleEndDate: ").append(internetSaleEndDate).append("\n");
    sb.append("  saleStartDate: ").append(saleStartDate).append("\n");
    sb.append("  saleEndDate: ").append(saleEndDate).append("\n");
    sb.append("  memberSaleStartDate: ").append(memberSaleStartDate).append("\n");
    sb.append("  memberSaleEndDate: ").append(memberSaleEndDate).append("\n");
    sb.append("  eventDate: ").append(eventDate).append("\n");
    sb.append("  eventTime: ").append(eventTime).append("\n");
    sb.append("  stadiumName: ").append(stadiumName).append("\n");
    sb.append("  city: ").append(city).append("\n");
    sb.append("  state: ").append(state).append("\n");
    sb.append("  principalClub: ").append(principalClub).append("\n");
    sb.append("  opponentClub: ").append(opponentClub).append("\n");
    sb.append("  principalClubImage: ").append(principalClubImage).append("\n");
    sb.append("  opponentClubImage: ").append(opponentClubImage).append("\n");
    sb.append("  expressSale: ").append(expressSale).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
