/**
 * API do Futebolcard
 * Futebolcard manipulation API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.sensedia.futcardclient.model;

import java.util.*;
import java.util.Map;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Sectors {
  
  @SerializedName("gates")
  private List<Gates> gates = null;
  @SerializedName("map")
  private Map map = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Gates> getGates() {
    return gates;
  }
  public void setGates(List<Gates> gates) {
    this.gates = gates;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Map getMap() {
    return map;
  }
  public void setMap(Map map) {
    this.map = map;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Sectors sectors = (Sectors) o;
    return (this.gates == null ? sectors.gates == null : this.gates.equals(sectors.gates)) &&
        (this.map == null ? sectors.map == null : this.map.equals(sectors.map));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.gates == null ? 0: this.gates.hashCode());
    result = 31 * result + (this.map == null ? 0: this.map.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Sectors {\n");
    
    sb.append("  gates: ").append(gates).append("\n");
    sb.append("  map: ").append(map).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
