/**
 * API do Futebolcard
 * Futebolcard manipulation API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.sensedia.futcardclient.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SubSectorDetails {
  
  @SerializedName("subsectorId")
  private String subsectorId = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("hasTickets")
  private Integer hasTickets = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSubsectorId() {
    return subsectorId;
  }
  public void setSubsectorId(String subsectorId) {
    this.subsectorId = subsectorId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getHasTickets() {
    return hasTickets;
  }
  public void setHasTickets(Integer hasTickets) {
    this.hasTickets = hasTickets;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubSectorDetails subSectorDetails = (SubSectorDetails) o;
    return (this.subsectorId == null ? subSectorDetails.subsectorId == null : this.subsectorId.equals(subSectorDetails.subsectorId)) &&
        (this.name == null ? subSectorDetails.name == null : this.name.equals(subSectorDetails.name)) &&
        (this.hasTickets == null ? subSectorDetails.hasTickets == null : this.hasTickets.equals(subSectorDetails.hasTickets));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.subsectorId == null ? 0: this.subsectorId.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.hasTickets == null ? 0: this.hasTickets.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubSectorDetails {\n");
    
    sb.append("  subsectorId: ").append(subsectorId).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  hasTickets: ").append(hasTickets).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
