/**
 * API dos Correios
 * API de rastreios de Objetos Postais
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.com.sensedia.correios.api.v1.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Customer Model
 **/
@ApiModel(description = "Customer Model")
public class DetalhesEventos {
  
  @SerializedName("tipoEvento")
  private String tipoEvento = null;
  @SerializedName("statusEvento")
  private Integer statusEvento = null;
  @SerializedName("descricaoEvento")
  private String descricaoEvento = null;

  /**
   * TIpo do Evento
   **/
  @ApiModelProperty(value = "TIpo do Evento")
  public String getTipoEvento() {
    return tipoEvento;
  }
  public void setTipoEvento(String tipoEvento) {
    this.tipoEvento = tipoEvento;
  }

  /**
   * Status do Evento
   **/
  @ApiModelProperty(value = "Status do Evento")
  public Integer getStatusEvento() {
    return statusEvento;
  }
  public void setStatusEvento(Integer statusEvento) {
    this.statusEvento = statusEvento;
  }

  /**
   * Descrição do Evento
   **/
  @ApiModelProperty(value = "Descrição do Evento")
  public String getDescricaoEvento() {
    return descricaoEvento;
  }
  public void setDescricaoEvento(String descricaoEvento) {
    this.descricaoEvento = descricaoEvento;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DetalhesEventos detalhesEventos = (DetalhesEventos) o;
    return (this.tipoEvento == null ? detalhesEventos.tipoEvento == null : this.tipoEvento.equals(detalhesEventos.tipoEvento)) &&
        (this.statusEvento == null ? detalhesEventos.statusEvento == null : this.statusEvento.equals(detalhesEventos.statusEvento)) &&
        (this.descricaoEvento == null ? detalhesEventos.descricaoEvento == null : this.descricaoEvento.equals(detalhesEventos.descricaoEvento));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.tipoEvento == null ? 0: this.tipoEvento.hashCode());
    result = 31 * result + (this.statusEvento == null ? 0: this.statusEvento.hashCode());
    result = 31 * result + (this.descricaoEvento == null ? 0: this.descricaoEvento.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DetalhesEventos {\n");
    
    sb.append("  tipoEvento: ").append(tipoEvento).append("\n");
    sb.append("  statusEvento: ").append(statusEvento).append("\n");
    sb.append("  descricaoEvento: ").append(descricaoEvento).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
