/**
 * API dos Correios
 * API de rastreios de Objetos Postais
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.com.sensedia.correios.api.v1.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Customer Model
 **/
@ApiModel(description = "Customer Model")
public class Eventos {
  
  @SerializedName("codigoObjeto")
  private String codigoObjeto = null;
  @SerializedName("tipoEvento")
  private String tipoEvento = null;
  @SerializedName("statusEvento")
  private Integer statusEvento = null;
  @SerializedName("descricaoEvento")
  private String descricaoEvento = null;
  @SerializedName("nomeUnidade")
  private String nomeUnidade = null;
  @SerializedName("codigoSRO")
  private String codigoSRO = null;
  @SerializedName("municipio")
  private String municipio = null;
  @SerializedName("uf")
  private String uf = null;
  @SerializedName("codigoMCU")
  private String codigoMCU = null;
  @SerializedName("codigoDR")
  private String codigoDR = null;
  @SerializedName("siglaDR")
  private String siglaDR = null;
  @SerializedName("numeroLista")
  private String numeroLista = null;
  @SerializedName("estacao")
  private Integer estacao = null;
  @SerializedName("usuario")
  private String usuario = null;
  @SerializedName("dataGravacao")
  private String dataGravacao = null;
  @SerializedName("entregador")
  private String entregador = null;
  @SerializedName("dataCriacao")
  private String dataCriacao = null;
  @SerializedName("acaoBloqueio")
  private Integer acaoBloqueio = null;

  /**
   * Código do Objeto
   **/
  @ApiModelProperty(value = "Código do Objeto")
  public String getCodigoObjeto() {
    return codigoObjeto;
  }
  public void setCodigoObjeto(String codigoObjeto) {
    this.codigoObjeto = codigoObjeto;
  }

  /**
   * Tipo do Evento
   **/
  @ApiModelProperty(value = "Tipo do Evento")
  public String getTipoEvento() {
    return tipoEvento;
  }
  public void setTipoEvento(String tipoEvento) {
    this.tipoEvento = tipoEvento;
  }

  /**
   * Status do Evento
   **/
  @ApiModelProperty(value = "Status do Evento")
  public Integer getStatusEvento() {
    return statusEvento;
  }
  public void setStatusEvento(Integer statusEvento) {
    this.statusEvento = statusEvento;
  }

  /**
   * Descrição do Evento
   **/
  @ApiModelProperty(value = "Descrição do Evento")
  public String getDescricaoEvento() {
    return descricaoEvento;
  }
  public void setDescricaoEvento(String descricaoEvento) {
    this.descricaoEvento = descricaoEvento;
  }

  /**
   * Nome da Unidade
   **/
  @ApiModelProperty(value = "Nome da Unidade")
  public String getNomeUnidade() {
    return nomeUnidade;
  }
  public void setNomeUnidade(String nomeUnidade) {
    this.nomeUnidade = nomeUnidade;
  }

  /**
   * Código do SRO
   **/
  @ApiModelProperty(value = "Código do SRO")
  public String getCodigoSRO() {
    return codigoSRO;
  }
  public void setCodigoSRO(String codigoSRO) {
    this.codigoSRO = codigoSRO;
  }

  /**
   * Nome do Municipio
   **/
  @ApiModelProperty(value = "Nome do Municipio")
  public String getMunicipio() {
    return municipio;
  }
  public void setMunicipio(String municipio) {
    this.municipio = municipio;
  }

  /**
   * Sigla do Estado
   **/
  @ApiModelProperty(value = "Sigla do Estado")
  public String getUf() {
    return uf;
  }
  public void setUf(String uf) {
    this.uf = uf;
  }

  /**
   * Código do MCU
   **/
  @ApiModelProperty(value = "Código do MCU")
  public String getCodigoMCU() {
    return codigoMCU;
  }
  public void setCodigoMCU(String codigoMCU) {
    this.codigoMCU = codigoMCU;
  }

  /**
   * Código DR
   **/
  @ApiModelProperty(value = "Código DR")
  public String getCodigoDR() {
    return codigoDR;
  }
  public void setCodigoDR(String codigoDR) {
    this.codigoDR = codigoDR;
  }

  /**
   * Sigla do DR
   **/
  @ApiModelProperty(value = "Sigla do DR")
  public String getSiglaDR() {
    return siglaDR;
  }
  public void setSiglaDR(String siglaDR) {
    this.siglaDR = siglaDR;
  }

  /**
   * Número na Lista
   **/
  @ApiModelProperty(value = "Número na Lista")
  public String getNumeroLista() {
    return numeroLista;
  }
  public void setNumeroLista(String numeroLista) {
    this.numeroLista = numeroLista;
  }

  /**
   * Estação
   **/
  @ApiModelProperty(value = "Estação")
  public Integer getEstacao() {
    return estacao;
  }
  public void setEstacao(Integer estacao) {
    this.estacao = estacao;
  }

  /**
   * Nome do Usuário
   **/
  @ApiModelProperty(value = "Nome do Usuário")
  public String getUsuario() {
    return usuario;
  }
  public void setUsuario(String usuario) {
    this.usuario = usuario;
  }

  /**
   * Data da Gravação
   **/
  @ApiModelProperty(value = "Data da Gravação")
  public String getDataGravacao() {
    return dataGravacao;
  }
  public void setDataGravacao(String dataGravacao) {
    this.dataGravacao = dataGravacao;
  }

  /**
   * Entregador
   **/
  @ApiModelProperty(value = "Entregador")
  public String getEntregador() {
    return entregador;
  }
  public void setEntregador(String entregador) {
    this.entregador = entregador;
  }

  /**
   * Data de Criação
   **/
  @ApiModelProperty(value = "Data de Criação")
  public String getDataCriacao() {
    return dataCriacao;
  }
  public void setDataCriacao(String dataCriacao) {
    this.dataCriacao = dataCriacao;
  }

  /**
   * Ação de Bloqueio
   **/
  @ApiModelProperty(value = "Ação de Bloqueio")
  public Integer getAcaoBloqueio() {
    return acaoBloqueio;
  }
  public void setAcaoBloqueio(Integer acaoBloqueio) {
    this.acaoBloqueio = acaoBloqueio;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Eventos eventos = (Eventos) o;
    return (this.codigoObjeto == null ? eventos.codigoObjeto == null : this.codigoObjeto.equals(eventos.codigoObjeto)) &&
        (this.tipoEvento == null ? eventos.tipoEvento == null : this.tipoEvento.equals(eventos.tipoEvento)) &&
        (this.statusEvento == null ? eventos.statusEvento == null : this.statusEvento.equals(eventos.statusEvento)) &&
        (this.descricaoEvento == null ? eventos.descricaoEvento == null : this.descricaoEvento.equals(eventos.descricaoEvento)) &&
        (this.nomeUnidade == null ? eventos.nomeUnidade == null : this.nomeUnidade.equals(eventos.nomeUnidade)) &&
        (this.codigoSRO == null ? eventos.codigoSRO == null : this.codigoSRO.equals(eventos.codigoSRO)) &&
        (this.municipio == null ? eventos.municipio == null : this.municipio.equals(eventos.municipio)) &&
        (this.uf == null ? eventos.uf == null : this.uf.equals(eventos.uf)) &&
        (this.codigoMCU == null ? eventos.codigoMCU == null : this.codigoMCU.equals(eventos.codigoMCU)) &&
        (this.codigoDR == null ? eventos.codigoDR == null : this.codigoDR.equals(eventos.codigoDR)) &&
        (this.siglaDR == null ? eventos.siglaDR == null : this.siglaDR.equals(eventos.siglaDR)) &&
        (this.numeroLista == null ? eventos.numeroLista == null : this.numeroLista.equals(eventos.numeroLista)) &&
        (this.estacao == null ? eventos.estacao == null : this.estacao.equals(eventos.estacao)) &&
        (this.usuario == null ? eventos.usuario == null : this.usuario.equals(eventos.usuario)) &&
        (this.dataGravacao == null ? eventos.dataGravacao == null : this.dataGravacao.equals(eventos.dataGravacao)) &&
        (this.entregador == null ? eventos.entregador == null : this.entregador.equals(eventos.entregador)) &&
        (this.dataCriacao == null ? eventos.dataCriacao == null : this.dataCriacao.equals(eventos.dataCriacao)) &&
        (this.acaoBloqueio == null ? eventos.acaoBloqueio == null : this.acaoBloqueio.equals(eventos.acaoBloqueio));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.codigoObjeto == null ? 0: this.codigoObjeto.hashCode());
    result = 31 * result + (this.tipoEvento == null ? 0: this.tipoEvento.hashCode());
    result = 31 * result + (this.statusEvento == null ? 0: this.statusEvento.hashCode());
    result = 31 * result + (this.descricaoEvento == null ? 0: this.descricaoEvento.hashCode());
    result = 31 * result + (this.nomeUnidade == null ? 0: this.nomeUnidade.hashCode());
    result = 31 * result + (this.codigoSRO == null ? 0: this.codigoSRO.hashCode());
    result = 31 * result + (this.municipio == null ? 0: this.municipio.hashCode());
    result = 31 * result + (this.uf == null ? 0: this.uf.hashCode());
    result = 31 * result + (this.codigoMCU == null ? 0: this.codigoMCU.hashCode());
    result = 31 * result + (this.codigoDR == null ? 0: this.codigoDR.hashCode());
    result = 31 * result + (this.siglaDR == null ? 0: this.siglaDR.hashCode());
    result = 31 * result + (this.numeroLista == null ? 0: this.numeroLista.hashCode());
    result = 31 * result + (this.estacao == null ? 0: this.estacao.hashCode());
    result = 31 * result + (this.usuario == null ? 0: this.usuario.hashCode());
    result = 31 * result + (this.dataGravacao == null ? 0: this.dataGravacao.hashCode());
    result = 31 * result + (this.entregador == null ? 0: this.entregador.hashCode());
    result = 31 * result + (this.dataCriacao == null ? 0: this.dataCriacao.hashCode());
    result = 31 * result + (this.acaoBloqueio == null ? 0: this.acaoBloqueio.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Eventos {\n");
    
    sb.append("  codigoObjeto: ").append(codigoObjeto).append("\n");
    sb.append("  tipoEvento: ").append(tipoEvento).append("\n");
    sb.append("  statusEvento: ").append(statusEvento).append("\n");
    sb.append("  descricaoEvento: ").append(descricaoEvento).append("\n");
    sb.append("  nomeUnidade: ").append(nomeUnidade).append("\n");
    sb.append("  codigoSRO: ").append(codigoSRO).append("\n");
    sb.append("  municipio: ").append(municipio).append("\n");
    sb.append("  uf: ").append(uf).append("\n");
    sb.append("  codigoMCU: ").append(codigoMCU).append("\n");
    sb.append("  codigoDR: ").append(codigoDR).append("\n");
    sb.append("  siglaDR: ").append(siglaDR).append("\n");
    sb.append("  numeroLista: ").append(numeroLista).append("\n");
    sb.append("  estacao: ").append(estacao).append("\n");
    sb.append("  usuario: ").append(usuario).append("\n");
    sb.append("  dataGravacao: ").append(dataGravacao).append("\n");
    sb.append("  entregador: ").append(entregador).append("\n");
    sb.append("  dataCriacao: ").append(dataCriacao).append("\n");
    sb.append("  acaoBloqueio: ").append(acaoBloqueio).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
