/**
 * API dos Correios
 * API de rastreios de Objetos Postais
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.com.sensedia.correios.api.v1.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Customer Model
 **/
@ApiModel(description = "Customer Model")
public class FaixaCEP {
  
  @SerializedName("nome")
  private String nome = null;
  @SerializedName("inicio")
  private String inicio = null;
  @SerializedName("fim")
  private String fim = null;

  /**
   * Nome do municipio
   **/
  @ApiModelProperty(value = "Nome do municipio")
  public String getNome() {
    return nome;
  }
  public void setNome(String nome) {
    this.nome = nome;
  }

  /**
   * inicio da faixa de CEP
   **/
  @ApiModelProperty(value = "inicio da faixa de CEP")
  public String getInicio() {
    return inicio;
  }
  public void setInicio(String inicio) {
    this.inicio = inicio;
  }

  /**
   * Fim da faixa de CEP
   **/
  @ApiModelProperty(value = "Fim da faixa de CEP")
  public String getFim() {
    return fim;
  }
  public void setFim(String fim) {
    this.fim = fim;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FaixaCEP faixaCEP = (FaixaCEP) o;
    return (this.nome == null ? faixaCEP.nome == null : this.nome.equals(faixaCEP.nome)) &&
        (this.inicio == null ? faixaCEP.inicio == null : this.inicio.equals(faixaCEP.inicio)) &&
        (this.fim == null ? faixaCEP.fim == null : this.fim.equals(faixaCEP.fim));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.nome == null ? 0: this.nome.hashCode());
    result = 31 * result + (this.inicio == null ? 0: this.inicio.hashCode());
    result = 31 * result + (this.fim == null ? 0: this.fim.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class FaixaCEP {\n");
    
    sb.append("  nome: ").append(nome).append("\n");
    sb.append("  inicio: ").append(inicio).append("\n");
    sb.append("  fim: ").append(fim).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
