/**
 * API dos Correios
 * API de rastreios de Objetos Postais
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.com.sensedia.correios.api.v1.model;

import br.com.sensedia.correios.api.v1.model.Eventos;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Postal Object model
 **/
@ApiModel(description = "Postal Object model")
public class ObjetoPostal {
  
  @SerializedName("numero")
  private String numero = null;
  @SerializedName("eventos")
  private List<Eventos> eventos = null;

  /**
   * Número do Objeto Postal
   **/
  @ApiModelProperty(value = "Número do Objeto Postal")
  public String getNumero() {
    return numero;
  }
  public void setNumero(String numero) {
    this.numero = numero;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Eventos> getEventos() {
    return eventos;
  }
  public void setEventos(List<Eventos> eventos) {
    this.eventos = eventos;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ObjetoPostal objetoPostal = (ObjetoPostal) o;
    return (this.numero == null ? objetoPostal.numero == null : this.numero.equals(objetoPostal.numero)) &&
        (this.eventos == null ? objetoPostal.eventos == null : this.eventos.equals(objetoPostal.eventos));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.numero == null ? 0: this.numero.hashCode());
    result = 31 * result + (this.eventos == null ? 0: this.eventos.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ObjetoPostal {\n");
    
    sb.append("  numero: ").append(numero).append("\n");
    sb.append("  eventos: ").append(eventos).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
